<bug id='655' author='adk9' open_date='2020-05-28T06:05:58Z' closed_time='2020-05-28T21:10:12Z'>
	<summary>ModuleNotFoundError: No module named 'openvino.inference_engine.constants'</summary>
	<description>
I built and installed the Python module by using the -DENABLE_PYTHON=ON CMake flag. When I try to load the Python module, I see the following error:
$ python test.py
Traceback (most recent call last):
  File "test.py", line 3, in &lt;module&gt;
    from openvino.inference_engine import IECore
  File "/home/adk/openvino_dist/python/python3.6/openvino/inference_engine/__init__.py", line 1, in &lt;module&gt;
    from .ie_api import *
  File "ie_api.pyx", line 23, in init openvino.inference_engine.ie_api
ModuleNotFoundError: No module named 'openvino.inference_engine.constants'
I'm using Python 3.6.9 and openvino master.
	</description>
	<comments>
		<comment id='1' author='adk9' date='2020-05-28T09:06:51Z'>
		&lt;denchmark-link:https://github.com/akuporos&gt;@akuporos&lt;/denchmark-link&gt;
, &lt;denchmark-link:https://github.com/nkogteva&gt;@nkogteva&lt;/denchmark-link&gt;
 can you help?
		</comment>
		<comment id='2' author='adk9' date='2020-05-28T09:19:59Z'>
		Hello &lt;denchmark-link:https://github.com/adk9&gt;@adk9&lt;/denchmark-link&gt;
,
Have you used the last OV master?
Looks like you built ie_api target, but it's need also build constants. But since last Friday there should be enough to build ie_api target.
Best regards,
Anastasia
		</comment>
		<comment id='3' author='adk9' date='2020-05-28T17:10:17Z'>
		Hi &lt;denchmark-link:https://github.com/akuporos&gt;@akuporos&lt;/denchmark-link&gt;
, I'm using the latest OV master. I'm not building any individual targets (if that's what you mean) but simply doing a  before trying to use the module. I see that a  is built but not installed. Is that the expected behavior?
		</comment>
		<comment id='4' author='adk9' date='2020-05-28T17:19:01Z'>
		Hello &lt;denchmark-link:https://github.com/adk9&gt;@adk9&lt;/denchmark-link&gt;
,
We haven't try  command, so it could cause  this problem.
Usually after  we just set  and run scripts.
So we need sometime to investigate how can we fix it after .
Best regards,
Anastasia
		</comment>
		<comment id='5' author='adk9' date='2020-05-28T20:05:44Z'>
		&lt;denchmark-link:https://github.com/adk9&gt;@adk9&lt;/denchmark-link&gt;
 I've provided a fix, could you please review as well and check whether it solves the issue?
		</comment>
		<comment id='6' author='adk9' date='2020-05-28T21:10:12Z'>
		Thanks &lt;denchmark-link:https://github.com/ilya-lavrenov&gt;@ilya-lavrenov&lt;/denchmark-link&gt;
, LGTM and it fixes the issue I was seeing.
		</comment>
	</comments>
</bug>