{"BR": {"BR_id": "3085", "BR_author": "igor-susic", "BRopenT": "2019-12-13T08:11:20Z", "BRcloseT": "2019-12-16T19:11:58Z", "BR_text": {"BRsummary": "Wrong path for `envs` subdirectory", "BRdescription": "\n Documentation bug:\n At  for <denchmark-link:https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Python-API.md>Python-API</denchmark-link>\n  in the section for <denchmark-link:https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Python-API.md#loading-a-unity-environment>loading-a-unity-environment</denchmark-link>\n  it states that the  is located at  but the subdirectory  does not exists there, should the path be  insted?\n \t"}, "comments": {"comments_0": {"comment_id": 1, "comment_author": "igor-susic", "commentT": "2019-12-16T18:42:05Z", "comment_text": "\n \t\tThanks for the report. I've got a PR to fix the location here <denchmark-link:https://github.com/Unity-Technologies/ml-agents/pull/3093>#3093</denchmark-link>\n \n \t\t"}}}, "commit": {"commit_id": "a228b0626093e95ad9874191c980b710f2164071", "commit_author": "Chris Elion", "commitT": "2019-12-16 11:11:45-08:00", "commit_complexity": {"commit_NLOC": "None", "commit_CCN": "None", "commit_Nprams": "None"}, "changed_files": {"file_0": {"file_change_type": "MODIFY", "file_Nmethod": 0, "file_old_name": "docs\\Python-API.md", "file_new_name": "docs\\Python-API.md", "file_complexity": {"file_NLOC": "None", "file_CCN": "None", "file_NToken": "None"}, "hunks": {"hunk_0": {"Ismethod": 0, "added_lines": "52,53,54", "deleted_lines": "52,53,54"}}}}}}