<bug id='1762' author='yantriks-edi-bice' open_date='2020-05-08T21:06:04Z' closed_time='2020-06-22T14:52:04Z'>
	<summary>Taxi transform step fails with "WriteToFile/Write/WriteImpl/InitializeWrite failed."</summary>
	<description>
I'm running (from notebook) on latest Kubeflow (IAP secured) a TFX pipeline based on the Taxi template. I had to create a custom image to use the latest TFX (0.22-dev) which includes a required bug fix. This version of TFX is apparently using Beam 2.20. Pipeline completed okay previously (with TFX 0.21.4 and Beam 2.17) albeit using BeamDagRunner instead of KubeflowDagRunner.
I've ran the pipeline twice and in both cases it failed at the same step at around the same time (another interesting thing is that now it no longer autoscales higher than a single worker whereas it used 2 workers when using BeamDagRunner)
Finished operation Analyze/VocabularyPrune[compute_and_apply_vocabulary_7/vocabulary]/ApplyFrequencyThresholdAndTopK/Top(10)/Create/Read+Analyze/VocabularyPrune[compute_and_apply_vocabulary_7/vocabulary]/ApplyFrequencyThresholdAndTopK/Top(10)/GroupByKey/Reify+Analyze/VocabularyPrune[compute_and_apply_vocabulary_7/vocabulary]/ApplyFrequencyThresholdAndTopK/Top(10)/GroupByKey/Write
INFO:apache_beam.runners.dataflow.dataflow_runner:2020-05-08T20:51:30.608Z: JOB_MESSAGE_WARNING: S675:Materialize[TransformIndex0]/Write/Write/WriteImpl/DoOnce/Read+Materialize[TransformIndex0]/Write/Write/WriteImpl/InitializeWrite failed.
	</description>
	<comments>
		<comment id='1' author='yantriks-edi-bice' date='2020-05-08T22:05:50Z'>
		Our previous TFX 0.21.4 release has some issues with Beam 2.20, we will update it in our next release
For notebook, beam multiprocessing might not work properly, could you try local examples?
		</comment>
		<comment id='2' author='yantriks-edi-bice' date='2020-05-11T14:20:22Z'>
		&lt;denchmark-link:https://github.com/1025KB&gt;@1025KB&lt;/denchmark-link&gt;
 I am using the latest TFX version 0.22-dev which uses Beam 2.20. This was achieved by passing the KubeflowDagRunner a config which points it to my custom tfx_image. I don't see how I can do that for the BeamDagRunner.
		</comment>
		<comment id='3' author='yantriks-edi-bice' date='2020-05-11T19:07:03Z'>
		Running the same pipeline from my laptop (not Kubeflow notebook) using BeamDagRunner works okay but then again it is using TFX 0.21.4 and Apache Beam 2.17 which is known to work and is listed in compatible versions page.
The reason for this issue is being forced to use the latest TFX version (0.22-dev which uses Beam 2.20) as it incorporates &lt;denchmark-link:url&gt;https://github.com/tensorflow/tfx/pull/1707&lt;/denchmark-link&gt;

Can that fix be ported to the currently supported TFX version (0.21.4 I believe)?
		</comment>
		<comment id='4' author='yantriks-edi-bice' date='2020-05-11T19:37:07Z'>
		For beam 2.20 support, it will be available in TFX 0.22 release.
		</comment>
		<comment id='5' author='yantriks-edi-bice' date='2020-05-29T18:28:33Z'>
		TFX 0.22. release will require beam&gt;=2.21,&lt;3.
		</comment>
		<comment id='6' author='yantriks-edi-bice' date='2020-06-22T14:52:04Z'>
		Working after updating to latest TFX and Beam
		</comment>
		<comment id='7' author='yantriks-edi-bice' date='2020-06-22T14:52:06Z'>
		Are you satisfied with the resolution of your issue?
&lt;denchmark-link:https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&amp;entry.2137816233=https://github.com/tensorflow/tfx/issues/1762&gt;Yes&lt;/denchmark-link&gt;

&lt;denchmark-link:https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&amp;entry.2137816233=https://github.com/tensorflow/tfx/issues/1762&gt;No&lt;/denchmark-link&gt;

		</comment>
	</comments>
</bug>