<bug id='19' author='XiaotianM' open_date='2017-08-27T13:56:20Z' closed_time='2017-09-02T05:26:13Z'>
	<summary>FileType Support?</summary>
	<description>
Hello, I have set up the Labelme. However, it seems to only support the filetype like *.b'bmp'...
So I donâ€˜t know how to use it. Besides, when I use your example codes, it has gone wrong. Problem presented as follows: "Error saving label data, a bytes-like object is required, not  'str' "
Can you tell me how to solve this problem? Thank you
	</description>
	<comments>
		<comment id='1' author='XiaotianM' date='2017-08-27T14:29:22Z'>
		Please specify your platform and the version of labelme and pyqt
		</comment>
		<comment id='2' author='XiaotianM' date='2017-08-28T02:32:18Z'>
		Win10 platform, Anaconda, and I install labelme by conda create --name=labelme python=3.5, and others are the same as your guidance
		</comment>
		<comment id='3' author='XiaotianM' date='2017-08-29T02:10:16Z'>
		Could you please paste below command's output?
&lt;denchmark-code&gt;conda list pyqt | grep pyqt
&lt;/denchmark-code&gt;

		</comment>
		<comment id='4' author='XiaotianM' date='2017-08-29T06:32:15Z'>
		pyqt 5.6.0 py35_0
I think pyqt is OK,
the labelme GUI is ok, but I can not load the image.
&lt;denchmark-link:https://user-images.githubusercontent.com/29722350/29807475-c341c2ec-8cc6-11e7-8802-8bf9dace31b8.png&gt;&lt;/denchmark-link&gt;

		</comment>
		<comment id='5' author='XiaotianM' date='2017-08-30T08:10:29Z'>
		I can not load my image, too.
		</comment>
		<comment id='6' author='XiaotianM' date='2017-09-02T05:07:43Z'>
		Confirmed. It is caused by the difference of string betwee python2 and 3.
Will be fixed via &lt;denchmark-link:https://github.com/wkentaro/labelme/pull/20&gt;#20&lt;/denchmark-link&gt;
.
		</comment>
	</comments>
</bug>